### ISSUE TITLE
Don't use Nominatim on every pageview/mapview

### ISSUE THREAD

**Issue by mtmail** [tanrax/openstreetmap-tag-map#1]
The tag calls the nominatim.openstreetmap.org service for every pageview only to gather the same latitude&longitude data. I think `<map latitude= longitude= zoom= height= width=>` would equally work.

Users of the tag should be made aware that the service might stop or get blocked anytime. See https://operations.osmfoundation.org/policies/nominatim/  For using `/export` see https://operations.osmfoundation.org/policies/tiles/

**Comment by tanrax** [comment]
The problem I encounter is when calculating in javascript the four boundingbox coordinates from longitude and latitude. Not counting the zoom variable. Could you give me an example? Thank you.

**Comment by mtmail** [comment]
You're right, you'd need a geocoder to return the boundaries of a place (e.g. city) at least once. Or ask users to supply those, e.g. via http://bboxfinder.com/ or such.

Closing since there isn't a clear solution.
